package one.dichmann.lectioapp.Fragments;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import downloadLectio.parseLesson;
import one.dichmann.lectioapp.R;
import permissions.fileManagement;
import schedule.Weekday;

public class DayFragment extends Fragment {

    public String gymID,nameID;

    private Calendar c = Calendar.getInstance();

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.day_frag, container, false);

        TextView day = (TextView) v.findViewById(R.id.schedule_DayAndDate_Day);
        TextView date = (TextView) v.findViewById(R.id.schedule_DayAndDate_Date);

        c.setTimeInMillis(getArguments().getLong("Date"));
        SimpleDateFormat s = new SimpleDateFormat("dd/MM-yyyy");//today down to every detail
        String format = s.format(c.getTime()); //new Date should have todays date after parsed since Date is generated by currentmillis

        day.setText(Weekday());
        date.setText(format);

        LinearLayout modules = (LinearLayout) v.findViewById(R.id.schedule_Modules);

        String lessons = fileManagement.getFile(getContext(), gymID+nameID);
        String[] lesson = lessons.split("---");


        //modules.addView();
        return v;
    }

    public static DayFragment newInstance(Bundle b) {

        DayFragment f = new DayFragment();

        f.setArguments(b);

        return f;
    }

    public String Weekday() {
        Date date; //initialices date
        String weekDay = null;
        int dayOfWeek = c.get(Calendar.DAY_OF_WEEK); //gets a integer between to be compared with the weekday

        //checks which day it is
        if (Calendar.MONDAY == dayOfWeek) weekDay = "Mandag";
        else if (Calendar.TUESDAY == dayOfWeek) weekDay = "Tirsdag";
        else if (Calendar.WEDNESDAY == dayOfWeek) weekDay = "Onsdag";
        else if (Calendar.THURSDAY == dayOfWeek) weekDay = "Torsdag";
        else if (Calendar.FRIDAY == dayOfWeek) weekDay = "Fredag";
        else if (Calendar.SATURDAY == dayOfWeek) weekDay = "Lørdag";
        else if (Calendar.SUNDAY == dayOfWeek) weekDay = "Søndag";

        return weekDay;//returns day after it is convertet to a string
    }
}
