package one.dichmann.lectioapp.Fragments;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import downloadLectio.parseLesson;
import one.dichmann.lectioapp.LoadingActivity;
import one.dichmann.lectioapp.LoginActivity;
import one.dichmann.lectioapp.R;
import one.dichmann.lectioapp.ScheduleActivity;

public class WeekFragment extends Fragment {

    public Activity context;

    public String gymID, nameID;
    public String file, lessons;
    public String timeStamp, parse, todayDate;
    public String week, year;

    private LinearLayout.LayoutParams moduleLLParams = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT, 1.0f);
    private LinearLayout.LayoutParams dayLLParams = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT, 1.0f);

    public Calendar c = Calendar.getInstance();

    @Override
    public void onAttach(Context activity) {
        super.onAttach(activity);
        context = getActivity();
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        moduleLLParams.setMargins(15,20,15,20);

        View v = inflater.inflate(R.layout.week_frag, container, false);

        TextView weekNumber = (TextView) v.findViewById(R.id.schedule_weekNumber);

        LinearLayout weekLL = new LinearLayout(context);

        weekLL.setLayoutParams(dayLLParams);

        c.setTimeInMillis(getArguments().getLong("Date"));
        gymID = getArguments().getString("gymID");
        nameID = getArguments().getString("nameID");

        SimpleDateFormat s = new SimpleDateFormat("dd/MM-yyyy");//today down to every detail
        String format = s.format(c.getTime()); //new Date should have todays date after parsed since Date is generated by currentmillis

        String[] dateint = format.split("");

        todayDate = dateint[1].replace("0", "") + dateint[2] + "/" + dateint[4].replace("0", "") + dateint[5] + "-" + format.split("-")[1];

        int intweek = c.get(Calendar.WEEK_OF_YEAR);
        int length = String.valueOf(intweek).length(); //gets the amount of digits on the number
        if (length == 1) { //checks if the int is only one digit
            week = "0" + intweek;//lectio needs it to be doubledigit
        } else {
            week = "" + intweek;//function returns String
        }

        String weekNumberText = "uge " + intweek;
        weekNumber.setText(weekNumberText);
        weekNumber.setTextColor(getResources().getColor(R.color.schedule_TextColor));

        if  (new permissions.fileManagement().fileExists(context, gymID + nameID + week)) { //checks if a file with the schedule already exists
            timeStamp = schedule.Weekday.Today(); // creates a new timestamp whcih should be equal to the time of execution
            file = permissions.fileManagement.getFile(context, gymID + nameID + week);//loads the file to a string from Storage with the GetFile method from fileManagement
            parse = ("(.*?)(\\d\\d)(:)(\\d\\d)(:)(\\d\\d)"); // creates a pattern for the date method
            Pattern p = Pattern.compile(parse); //compiles the pattern
            Matcher m = p.matcher(timeStamp); //matches the pattern against the entire file
            Matcher m2 = p.matcher(file); //matches the pattern against the entire file
            if (m.find() && m2.find()) { //if both of them are equal they both contain valid date information and therefore we can see how old the file is
                int hour = Integer.parseInt(m.group(2)); //sets the hour of the timestamp
                int hour2 = Integer.parseInt(m2.group(2)); //sets the hour of the file´s timestamp

                if (!(hour2 + 1 < hour)) {//compares the 2 hour numbers. the schedule can at max be 2 hours old.
                    lessons = file.replace(String.valueOf(m2.group(0)), ""); //removes the date tag from the file before the content of the file is placed as our schedule
                }
            }

            String thisDay = "first";

            LinearLayout day = new LinearLayout(context);
            day.setOrientation(LinearLayout.VERTICAL);
            day.setLayoutParams(dayLLParams);
            day.setGravity(Gravity.CENTER);

            if (lessons != null) {
                String[] lesson = lessons.split("£");
                for (int i = 0; i < lesson.length; i++) {
                    if (thisDay != null) {
                        String time = parseLesson.getDate(lesson[i]);
                        if (thisDay.equals(time) || thisDay.equals("first")) {
                            thisDay = time;
                            String team = parseLesson.getTeam(lesson[i]);
                            String teacher = parseLesson.getTeacher(lesson[i]);
                            String room = parseLesson.getRoom(lesson[i]);
                            if (team != null) {
                                Pattern teamRegex = Pattern.compile("Alle");
                                Matcher teamMatcher = teamRegex.matcher(team);
                                if (room != null) {
                                    Pattern roomRegex = Pattern.compile("\\,(.*?)(\\,|$)");
                                    Matcher roomMatcher = roomRegex.matcher(room);
                                    if (roomMatcher.find()) {
                                        room = roomMatcher.group(1);
                                    }
                                }
                                if (!teamMatcher.find()) {
                                    String[] module = new String[]{team, teacher, room};
                                    LinearLayout moduleLL = new LinearLayout(context);
                                    moduleLL.setOrientation(LinearLayout.VERTICAL);
                                    moduleLL.setLayoutParams(moduleLLParams);
                                    moduleLL.setGravity(Gravity.CENTER);
                                    moduleLL.setBackgroundColor(getResources().getColor(R.color.schedule_Regular));
                                    for (int u = 0; u < 3; u++) {
                                        TextView moduleVertical = new TextView(context);
                                        moduleVertical.setText(module[u]);
                                        moduleVertical.setTextSize(15);
                                        moduleVertical.setPadding(10, 10, 10, 10);
                                        moduleVertical.setGravity(Gravity.CENTER);
                                        moduleVertical.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT));
                                        moduleVertical.setTextColor(getResources().getColor(R.color.schedule_TextColor));
                                        moduleLL.addView(moduleVertical);
                                    }
                                    day.addView(moduleLL);
                                }
                            }
                        } else if (time != null){
                            String team = parseLesson.getTeam(lesson[i]);
                            String teacher = parseLesson.getTeacher(lesson[i]);
                            String room = parseLesson.getRoom(lesson[i]);
                            if (team != null) {
                                Pattern teamRegex = Pattern.compile("Alle");
                                Matcher teamMatcher = teamRegex.matcher(team);
                                if (room != null) {
                                    Pattern roomRegex = Pattern.compile("\\,(.*?)(\\,|$)");
                                    Matcher roomMatcher = roomRegex.matcher(room);
                                    if (roomMatcher.find()) {
                                        room = roomMatcher.group(1);
                                    }
                                }
                                if (!teamMatcher.find()) {
                                    thisDay = time;
                                    weekLL.addView(day);

                                    day = new LinearLayout(context);
                                    day.setOrientation(LinearLayout.VERTICAL);
                                    day.setLayoutParams(dayLLParams);
                                    day.setGravity(Gravity.CENTER);

                                    String[] module = new String[]{team, teacher, room};
                                    LinearLayout moduleLL = new LinearLayout(context);
                                    moduleLL.setOrientation(LinearLayout.VERTICAL);
                                    moduleLL.setLayoutParams(moduleLLParams);
                                    moduleLL.setGravity(Gravity.CENTER);
                                    moduleLL.setBackgroundColor(getResources().getColor(R.color.schedule_Regular));
                                    for (int u = 0; u < 3; u++) {
                                        TextView moduleVertical = new TextView(context);
                                        moduleVertical.setText(module[u]);
                                        moduleVertical.setTextSize(15);
                                        moduleVertical.setPadding(10, 10, 10, 10);
                                        moduleVertical.setGravity(Gravity.CENTER);
                                        moduleVertical.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT));
                                        moduleVertical.setTextColor(getResources().getColor(R.color.schedule_TextColor));
                                        moduleLL.addView(moduleVertical);
                                    }
                                    day.addView(moduleLL);
                                }
                            }
                        }
                    }
                }
            }
            weekLL.addView(day);
            ((LinearLayout) v.findViewById(R.id.schedule_week)).addView(weekLL);
        } else {
            Button myButton = new Button(context);
            myButton.setOnClickListener(new View.OnClickListener() {
                public void onClick(View v) {

                    Intent intent = new Intent(context, LoadingActivity.class);
                    intent.putExtra(LoadingActivity.finalIntent, "Extra");
                    intent.putExtra(ScheduleActivity.finalLong, c.getTimeInMillis());
                    intent.putExtra(LoginActivity.finalNameID, nameID);
                    intent.putExtra(LoginActivity.finalGymID, gymID);
                    context.startActivity(intent);
                }
            });
            myButton.setText("Download Skema");

            LinearLayout ll = (LinearLayout) v.findViewById(R.id.schedule_week);
            LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT, 1f);
            lp.gravity = Gravity.CENTER;
            ll.addView(myButton, lp);
        }
        return v;
    }

    public static WeekFragment newInstance(Bundle b) {

        WeekFragment f = new WeekFragment();

        f.setArguments(b);

        return f;
    }

    public String Weekday() {
        String weekDay = null;
        int dayOfWeek = c.get(Calendar.DAY_OF_WEEK); //gets a integer between to be compared with the weekday

        //checks which day it is
        if (Calendar.MONDAY == dayOfWeek) weekDay = "Mandag";
        else if (Calendar.TUESDAY == dayOfWeek) weekDay = "Tirsdag";
        else if (Calendar.WEDNESDAY == dayOfWeek) weekDay = "Onsdag";
        else if (Calendar.THURSDAY == dayOfWeek) weekDay = "Torsdag";
        else if (Calendar.FRIDAY == dayOfWeek) weekDay = "Fredag";
        else if (Calendar.SATURDAY == dayOfWeek) weekDay = "Lørdag";
        else if (Calendar.SUNDAY == dayOfWeek) weekDay = "Søndag";

        return weekDay;//returns day after it is convertet to a string
    }
}
